spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: tsui-service-zuul
  zipkin:
    base-url: http://localhost:9998 #所有的数据提交到此服务之中
    sender:
      type: web       #提交的类型是web 服务
    sleuth:
      sampler:
        probability: 1.0 # 定义抽样比率，默认为0.1

zuul:
  routes:
    api-product:
      path: /api-product/**
      serviceId: tsui-service-product
    api-order:
      path: /api-order/**
      serviceId: tsui-service-order

server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: tsui-service-zuul
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds:  2