spring:
  profiles:
    active:
      - dev
---
server:
  port: 9001

spring:
  profiles: dev
  application:
    name: tsui-eureka-server

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false