spring:
  profiles:
    active:
      - dev
---
server:
  port: 9001

spring:
  profiles: dev
  application:
    name: tsui-eureka-server
  zipkin:
    base-url: http://192.168.1.130:9411 #所有的数据提交到此服务之中
    sender:
      type: web       #提交的类型是web 服务
    sleuth:
      sampler:
        probability: 1.0 # 定义抽样比率，默认为0.1

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
