spring:
  profiles:
    active:
      - dev
---

spring:
  profiles: dev
  application:
    name: tsui-service-users
  server:
    port: 9010
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:9001/eureka/
    instance:
      instance-id: tsui-service-users
      prefer-ip-address: true
      lease-expiration-duration-in-seconds: 5
      lease-renewal-interval-in-seconds:  2