spring:
  profiles:
    active:
      - dev

---

spring:
  profiles: dev
  application:
    name: tsui-service-product
  zipkin:
    base-url: http://192.168.1.130:9411 #所有的数据提交到此服务之中
#    sender:
#      type: web       #提交的类型是web 服务
    sleuth:
      sampler:
        probability: 1.0 # 定义抽样比率，默认为0.1

server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: tsui-service-product
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds:  2

info:
  app.name: tsui-service-product
  company.name: tsui