server:
  port: 9010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: tsui-service-product
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds:  2

spring:
  application:
    name: tsui-service-product
