server:
  port: 9998
spring:
  application:
    name: tsui-service-zipkin

management:
  metrics:
    web:
      server:
        auto-time-requests: false

zipkin:
  collector:
    sample-rate: 1.0
    http:
      enabled: false
    rabbitmq:
      addresses: 192.168.1.130:5672
      password: guest
      queue: zipkin
      username: guest
      virtual-host: /
  storage:
    type: mysql
    mysql:
      host: 192.168.1.130
      port: 3306
      username: root
      password: cdm0928
      db: zipkin


