spring:
  application:
    name: tsui-service-test
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: 192.168.1.130
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
