server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: tsui-service-zuul
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds:  2

spring:
  application:
    name: tsui-service-zuul
zuul:
  routes:
    api-product:
      path: /api-product/**
      serviceId: tsui-service-product
    api-order:
      path: /api-order/**
      serviceId: tsui-service-order
