#spring.application.name=config-server
#server.port=8889

#spring.cloud.config.server.git.uri=https://github.com/cuidm33/tsui-shiny-parent.git
#spring.cloud.config.server.git.searchPaths=respo
#spring.cloud.config.label=master
#spring.cloud.config.server.git.username=
#spring.cloud.config.server.git.password=

#eureka.client.serviceUrl.defaultZone=http://localhost:8889/eureka/

server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuidm33/tsui-shiny-parent.git
          username:
          password:
          search-paths: respo
      label: master
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
