
spring:
  #profiles: dev1
  application:
    name: tsui-config-server
    server:
      port: 8888
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/cuidm33/tsui-shiny-parent.git
          #uri: https://github.com/forezp/SpringcloudConfig.git
          searchPaths: respo


#eureka:
  #instance:
    #hostname: tsui-config-server
